export { default as Dashboard } from '../images/icons/dashboard.png';
export { default as Product } from '../images/icons/product.png';
export { default as CreateProduct } from '../images/icons/create_product.png';
export { default as ProductList } from '../images/icons/product_list.png';
export { default as chooseFile } from '../images/icons/choose_file.png';
export { default as User } from '../images/user/profile.png';
export { default as English } from '../images/icons/english.jpg';
export { default as Category } from '../images/icons/category.png';
export { default as Sales } from '../images/icons/sales.png'
export { default as Purchases } from '../images/icons/purchases.png';
export { default as Returns } from '../images/icons/returns.png';
export { default as CustomerList } from '../images/icons/customer_list.png';
export { default as Khmer } from '../images/icons/khmer.png';